# SSL Configuration
# Add all your domains here. The first domain will be used as the certificate name.

EMAIL="bkushwaha.dev@gmail.com"
CERT_NAME="cors-proxy.brijeshdev.space" # Do not change this unless you update nginx configs too

# Cloudflare API Token is loaded from the project root .env file (CLOUDFLARE_API_TOKEN)
# If not found there, set it here:
# CLOUDFLARE_API_TOKEN=""

DOMAINS=(
    "cors-proxy.brijeshdev.space"
    "cors-proxy2.brijeshdev.space"
    "api-cors-proxy.brijeshdev.space"
    "getdata-cors-proxy.brijeshdev.space"
    "brijeshdev.space"
    "portfolio.brijeshdev.space"
    "ranju.brijeshdev.space"
    "subsnepal.brijeshdev.space"
    "api-subsnepal.brijeshdev.space"
    "api.muncipal.brijeshdev.space"
)
